name: API Docs
on:
  push:
    branches:
      - main
      - '!dependabot/**'
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up node env
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '12.x'

      - name: Cache modules
        uses: actions/cache@v2.1.6
        id: restore-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Configure npm
        run: |-
         echo "//npm.pkg.github.com/:_authToken=\${NPM_AUTH_TOKEN}" > .npmrc
         echo "@rdipardo:registry=https://npm.pkg.github.com" >> .npmrc

      - name: Build docs
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |-
         npm install jsdoc @rdipardo/clean-jsdoc
         npx jsdoc www/js -c .github/jsdoc/conf.json -t node_modules/@rdipardo/clean-jsdoc

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          enable_jekyll: false
          publish_dir: ./doc
          user_name: 'github-actions[bot]'
          user_email: 'github-actions@users.noreply.github.com'
          commit_message: '[skip ci] ${{ github.event.head_commit.message }}'
